apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
  namespace: argocd
spec:
  template:
    spec:
      volumes:
        - name: gitops-tools
          emptyDir: {}
        # you already have this:
        - name: sops-age
          secret:
            secretName: sops-age
      initContainers:
        - name: install-helm-secrets-and-sops
          image: alpine:3.20
          command: ["/bin/sh","-c"]
          args:
            - |
              set -eux
              apk add --no-cache bash wget tar coreutils
              mkdir -p /gitops-tools/helm-plugins
              # install helm-secrets plugin
              wget -qO- https://github.com/jkroepke/helm-secrets/releases/download/v4.6.10/helm-secrets.tar.gz \
                | tar -C /gitops-tools/helm-plugins -xz
              # install sops binary (used by the plugin)
              ARCH="$(uname -m | sed -e 's/x86_64/amd64/' -e 's/aarch64/arm64/')"
              wget -qO /gitops-tools/sops https://github.com/getsops/sops/releases/download/v3.11.0/sops-v3.11.0.linux.${ARCH}
              chmod +x /gitops-tools/sops
              # place wrapper as "helm" to override the real binary via subPath mount
              cp /gitops-tools/helm-plugins/helm-secrets/scripts/wrapper/helm.sh /gitops-tools/helm
              chmod +x /gitops-tools/helm
          volumeMounts:
            - name: gitops-tools
              mountPath: /gitops-tools
      containers:
        - name: argocd-repo-server
          env:
            - name: HELM_PLUGINS
              value: /gitops-tools/helm-plugins
            - name: HELM_SECRETS_BACKEND
              value: sops
            - name: HELM_SECRETS_WRAPPER_ENABLED
              value: "true"
            - name: HELM_SECRETS_VALUES_ALLOW_ABSOLUTE_PATH
              value: "true"
            - name: HELM_SECRETS_SOPS_PATH
              value: /gitops-tools/sops
            - name: SOPS_AGE_KEY_FILE
              value: /sops/age.agekey
          volumeMounts:
            # override helm with the wrapper (only this file)
            - name: gitops-tools
              mountPath: /usr/local/sbin/helm
              subPath: helm
            - name: sops-age
              mountPath: /sops
              readOnly: true

