apiVersion: v1
kind: Namespace
metadata:
  name: openstack
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: neutron-ovn-confgen
  namespace: openstack
  labels:
    app.kubernetes.io/name: neutron-ovn-confgen
    application: neutron
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: neutron-ovn-confgen
  namespace: openstack
rules:
  - apiGroups: [""]
    resources: ["services","endpoints","endpointslices","configmaps"]
    verbs: ["get","list","watch","create","update","patch","delete"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get","list","watch","update","patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: neutron-ovn-confgen
  namespace: openstack
subjects:
  - kind: ServiceAccount
    name: neutron-ovn-confgen
    namespace: openstack
roleRef:
  kind: Role
  name: neutron-ovn-confgen
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: neutron-ovn-conn
  namespace: openstack
  labels:
    app.kubernetes.io/name: neutron-ovn-confgen
    application: neutron
data: {}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: neutron-ovn-confgen
  namespace: openstack
  annotations:
    argocd.argoproj.io/sync-wave: "35"
  labels:
    app.kubernetes.io/name: neutron-ovn-confgen
    application: neutron
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: neutron-ovn-confgen
        application: neutron
    spec:
      serviceAccountName: neutron-ovn-confgen
      restartPolicy: OnFailure
      containers:
        - name: confgen
          image: lachlanevenson/k8s-kubectl:v1.30.0
          command: ["/bin/sh","-c"]
          args:
            - |
              set -euo pipefail
              ns="openstack"
              nb_svc="ovn-ovsdb-nb"
              sb_svc="ovn-ovsdb-sb"

              # Resolve ClusterIPs
              nb_ip="$(kubectl -n "$ns" get svc "$nb_svc" -o jsonpath='{.spec.clusterIP}')"
              sb_ip="$(kubectl -n "$ns" get svc "$sb_svc" -o jsonpath='{.spec.clusterIP}')"

              # Helper to pick TLS if present, else TCP
              pick_port() {
                svc="$1"; tls1="$2"; tcp1="$3"
                ports="$(kubectl -n "$ns" get endpoints "$svc" -o jsonpath='{range .subsets[*].ports[*]}{.port}{"\n"}{end}' || true)"
                if echo "$ports" | grep -qx "$tls1"; then echo "$tls1 ssl"; elif echo "$ports" | grep -qx "$tcp1"; then echo "$tcp1 tcp"; else echo "$tcp1 tcp"; fi
              }

              read nb_port nb_proto <<EOF
              $(pick_port "$nb_svc" 6643 6641)
              EOF
              read sb_port sb_proto <<EOF
              $(pick_port "$sb_svc" 6644 6642)
              EOF

              ovn_nb="${nb_proto}:${nb_ip}:${nb_port}"
              ovn_sb="${sb_proto}:${sb_ip}:${sb_port}"

              cat > /tmp/10-ovn-connections.ini <<EOF
              [ovn]
              ovn_nb_connection = ${ovn_nb}
              ovn_sb_connection = ${ovn_sb}
              neutron_sync_mode = repair
              EOF

              # Recreate CM atomically
              kubectl -n "$ns" delete configmap neutron-ovn-conn --ignore-not-found
              kubectl -n "$ns" create configmap neutron-ovn-conn \
                --from-file=10-ovn-connections.ini=/tmp/10-ovn-connections.ini

              # Strategic-merge patch (YAML) – avoids JSON here-docs
              cat > /tmp/patch.yaml <<'PYAML'
              spec:
                template:
                  spec:
                    volumes:
                      - name: neutron-ovn-conn
                        configMap:
                          name: neutron-ovn-conn
                          optional: true
                    initContainers:
                      - name: inject-ovn-conn
                        image: busybox:1.36
                        command: ["/bin/sh","-c"]
                        args:
                          - >-
                            set -e;
                            mkdir -p /etc/neutron/neutron.conf.d;
                            if [ -f /ovn-snippet/10-ovn-connections.ini ]; then
                              cp /ovn-snippet/10-ovn-connections.ini /etc/neutron/neutron.conf.d/;
                            fi
                        volumeMounts:
                          - name: neutron-ovn-conn
                            mountPath: /ovn-snippet
                          - name: neutron-etc
                            mountPath: /etc/neutron
                    containers:
                      - name: neutron-server
                        volumeMounts:
                          - name: neutron-ovn-conn
                            mountPath: /etc/neutron/neutron.conf.d/10-ovn-connections.ini
                            subPath: 10-ovn-connections.ini
                            readOnly: true
              PYAML

              # Apply patch and restart rollout to pick CM immediately
              kubectl -n "$ns" patch deploy neutron-server --type=merge --patch-file /tmp/patch.yaml || true
              kubectl -n "$ns" rollout restart deploy neutron-server || true

