apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openstack-root
  namespace: argocd
spec:
  project: openstack
  source:
    repoURL: ssh://git@github.com/brunodzogovic/openstack-gitops.git
    targetRevision: main
    path: apps
    helm:
      valueFiles:
        - values.yaml
        - values/envs/prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions: 
      - CreateNamespace=true
      - ServerSideApply=true
      - PrunePropagationPolicy=foreground
      - ApplyOutOfSyncOnly=true
