apiVersion: batch/v1
kind: Job
metadata:
  name: keystone-db-reconcile
  namespace: openstack
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation,HookSucceeded
spec:
  ttlSecondsAfterFinished: 300
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: reconcile
        image: mysql:8.0
        env:
        - name: ADMIN_URL
          valueFrom: { secretKeyRef: { name: keystone-db-admin, key: DB_CONNECTION } }
        - name: USER_URL
          valueFrom:  { secretKeyRef: { name: keystone-db-user,  key: DB_CONNECTION } }
        command: ["/bin/sh","-lc"]
        args:
        - |
          set -euo pipefail
          host=$(printf "%s\n" "$ADMIN_URL" | sed -E 's#.*@([^:/]+).*#\1#')
          admin_pass=$(printf "%s\n" "$ADMIN_URL" | sed -E 's#^[^:]+://[^:]+:([^@]+)@.*#\1#')
          user_pass=$(printf "%s\n" "$USER_URL"  | sed -E 's#^[^:]+://[^:]+:([^@]+)@.*#\1#')

          mysql -h "$host" -uroot -p"$admin_pass" <<SQL
          CREATE DATABASE IF NOT EXISTS keystone;
          DROP USER IF EXISTS 'keystone'@'%';
          CREATE USER 'keystone'@'%' IDENTIFIED BY '${user_pass}';
          GRANT ALL PRIVILEGES ON keystone.* TO 'keystone'@'%';
          FLUSH PRIVILEGES;
          SQL

          echo "Smoke test as keystone…"
          mysql -h "$host" -ukeystone -p"$user_pass" -e "SELECT 1;"
          echo "OK."
