# manifests/keystone-db-password-fix.yaml  (one-time debug version)
apiVersion: batch/v1
kind: Job
metadata:
  name: keystone-db-password-fix-verify
  namespace: openstack
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: fix
        image: mysql:8.0
        env:
          - name: ADMIN_URL
            valueFrom: { secretKeyRef: { name: keystone-db-admin, key: DB_CONNECTION } }
          - name: USER_URL
            valueFrom:  { secretKeyRef: { name: keystone-db-user,  key: DB_CONNECTION } }
        command: ["/bin/sh","-lc"]
        args:
          - |
            set -euo pipefail
            host=$(printf "%s\n" "$ADMIN_URL" | sed -E 's#.*@([^:/]+).*#\1#')
            admin_pass=$(printf "%s\n" "$ADMIN_URL" | sed -E 's#^[^:]+://[^:]+:([^@]+)@.*#\1#')
            user_pass=$(printf "%s\n" "$USER_URL"  | sed -E 's#^[^:]+://[^:]+:([^@]+)@.*#\1#')

            echo "Using host=$host"
            mysql -h "$host" -uroot -p"$admin_pass" -e "
              CREATE DATABASE IF NOT EXISTS keystone;
              CREATE USER IF NOT EXISTS 'keystone'@'%' IDENTIFIED BY '${user_pass}';
              ALTER  USER 'keystone'@'%' IDENTIFIED BY '${user_pass}';
              GRANT ALL PRIVILEGES ON keystone.* TO 'keystone'@'%';
              FLUSH PRIVILEGES;"
            echo "Done."
