apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: {{ .Values.project }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.namespaces.rook }}
  source:
    repoURL: {{ .Values.repos.rook }}
    chart: rook-ceph
    targetRevision: {{ .Values.versions.rook_operator | default "v1.15.7" }}
    helm:
      valueFiles:
        - ../../values/rook/operator-values.yaml
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: ["CreateNamespace=true"]

