apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-cluster
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: {{ .Values.project }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.namespaces.rook }}
  source:
    repoURL: {{ .Values.repos.rook }}
    chart: rook-ceph-cluster
    targetRevision: {{ .Values.versions.rook.cluster }}
    helm:
      valueFiles:
        - ../../values/rook/cluster-values.yaml
  syncPolicy:
    automated: { prune: true, selfHeal: true }

