apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-ceph-os-objects
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "8"
spec:
  project: {{ .Values.project }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.namespaces.rook }}
  source:
    repoURL: {{ .Values.repos.osh }} # this is just a stub path for Argo to pull; we actually want local files
    targetRevision: {{ .Values.versions.osh_services_ref | default "master" }}
    path: ../../manifests/rook-ceph-os   # path INSIDE *your* repo; Argo resolves from your app's repo because of this relative path
  syncPolicy:
    automated: { prune: true, selfHeal: true }

