apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: osh-infra
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: {{ .Values.project }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.namespace.infra }}
  source:
    repoURL: {{ .Values.repos.osh_infra }}
    targetRevision: {{ .Values.versions.openstack.infra_ref }} # RECOMMENDED: replace with a pinned commit SHA
    path: helm-toolkit        # required dependency first
  syncPolicy:
    automated: { prune: true, selfHeal: true }
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: osh-infra-services
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "15"
spec:
  project: {{ .Values.project }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.namespace.infra }}
  source:
    repoURL: {{ .Values.repos.osh_infra }}
    targetRevision: {{ .Values.versions.openstack.infra_ref }}   # RECOMMENDED: pin to a commit SHA
    path: mariadb
    helm:
      valueFiles:
        - ../../values/globals.yaml
  syncPolicy:
    automated: { prune: true, selfHeal: true }
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: osh-rabbitmq
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "15"
spec:
  project: {{ .Values.project }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.namespaces.infra }}
  source:
    repoURL: {{ .Values.repos.osh_infra }}
    targetRevision: {{ .Values.versions.openstack.infra_ref }}
    path: rabbitmq
    helm:
      valueFiles:
        - ../../values/globals.yaml
  syncPolicy:
    automated: { prune: true, selfHeal: true }
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: osh-memcached
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "15"
spec:
  project: {{ .Values.project }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.namespaces.infra }}
  source:
    repoURL: {{ .Values.repos.osh_infra }}
    targetRevision: {{ .Values.versions.openstack.infra_ref }}
    path: memcached
    helm:
      valueFiles:
        - ../../values/globals.yaml
  syncPolicy:
    automated: { prune: true, selfHeal: true }

