apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keystone
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: {{ .Values.project }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.namespaces.os }}
  source:
    repoURL: {{ .Values.repos.osh }}
    targetRevision: {{ default "master" (dig "versions" "openstack" "services_ref" .Values) }} 
    path: keystone
    helm:
      valueFiles:
        - ../values/globals.yaml
        - ../values/secrets.sample.yaml
  syncPolicy:
    automated: { prune: true, selfHeal: true }

