apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nova
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  project: {{ .Values.project }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.namespaces.os }}
  sources:
    - repoURL: {{ .Values.repos.self }}
      targetRevision: {{ .Values.versions.self_ref | default "main" }}
      path: manifests
      directory:
        recurse: true
        include: ceph-bridge/**.yaml
    - repoURL: {{ .Values.repos.osh }}
      targetRevision: {{ .Values.versions.osh_services_ref | default "master" }}
      path: nova
      helm:
        valueFiles:
          - $values/values/globals.yaml
          - $values/values/nova-compute.yaml
          - $values/values/secrets/nova.secrets.sops.yaml
        postRenderer:
          kustomize:
            patches:
              # Make Cellv2 jobs re-run on each sync (helps while iterating)
              - target: { kind: Job, name: nova-db-init }
                patch: |
                  - op: add
                    path: /metadata/annotations/argocd.argoproj.io~1hook
                    value: Sync
                  - op: add
                    path: /metadata/annotations/argocd.argoproj.io~1hook-delete-policy
                    value: BeforeHookCreation
              - target: { kind: Job, name: nova-db-sync }
                patch: |
                  - op: add
                    path: /metadata/annotations/argocd.argoproj.io~1hook
                    value: Sync
                  - op: add
                    path: /metadata/annotations/argocd.argoproj.io~1hook-delete-policy
                    value: BeforeHookCreation
              - target: { kind: Job, name: nova-cell-setup }
                patch: |
                  - op: add
                    path: /metadata/annotations/argocd.argoproj.io~1hook
                    value: Sync
                  - op: add
                    path: /metadata/annotations/argocd.argoproj.io~1hook-delete-policy
                    value: BeforeHookCreation
              - target: { kind: Service, name: nova-api }
                patch: |
                  - op: replace
                    path: /spec/selector
                    value:
                      app.kubernetes.io/instance: nova
                      app.kubernetes.io/name: nova
                      app.kubernetes.io/component: os-api
                      application: nova
                      component: os-api
              # Remove the probes via postRenderer so the container isn’t killed before it opens the AMQP socket
              - target: { kind: Deployment, name: nova-scheduler }
                patch: |
                  - op: remove
                    path: /spec/template/spec/containers/0/livenessProbe
                  - op: remove
                    path: /spec/template/spec/containers/0/readinessProbe
              # (optional) repeat for nova-conductor
              - target: { kind: Deployment, name: nova-conductor }
                patch: |
                  - op: remove
                    path: /spec/template/spec/containers/0/livenessProbe
                  - op: remove
                    path: /spec/template/spec/containers/0/readinessProbe
    - repoURL: {{ .Values.repos.self }}
      targetRevision: {{ .Values.versions.self_ref | default "main" }}
      ref: values
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions:
      - ApplyOutOfSyncOnly=true
      #- Replace=true # keep Replace off here unless you need a first-time nuke of immutable fields
