apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: neutron
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "40"
spec:
  project: {{ .Values.project }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.namespaces.os }}
  sources:
    - repoURL: {{ .Values.repos.osh }}
      targetRevision: {{ .Values.versions.osh_services_ref | default "master" }}
      path: neutron
      helm:
        valueFiles:
          - $values/values/neutron-ovn.yaml   # ensure this is LAST so it wins!
          - $values/values/secrets/secrets.sops.yaml
        postRenderer:
          kustomize:
            patches:
              # --- Turn Helm-hooked jobs into Argo hooks (and/or plain Sync resources) ---
              - target: { kind: Job, name: neutron-db-init }
                patch: |
                  - op: add
                    path: /metadata/annotations/argocd.argoproj.io~1hook
                    value: Sync
                  - op: add
                    path: /metadata/annotations/argocd.argoproj.io~1hook-delete-policy
                    value: BeforeHookCreation
                  - op: remove
                    path: /metadata/annotations/helm.sh~1hook
                  - op: remove
                    path: /metadata/annotations/helm.sh~1hook-weight
              - target: { kind: Job, name: neutron-db-sync }
                patch: |
                  - op: add
                    path: /metadata/annotations/argocd.argoproj.io~1hook
                    value: Sync
                  - op: add
                    path: /metadata/annotations/argocd.argoproj.io~1hook-delete-policy
                    value: BeforeHookCreation
                  - op: remove
                    path: /metadata/annotations/helm.sh~1hook
                  - op: remove
                    path: /metadata/annotations/helm.sh~1hook-weight
              - target: { kind: Job, name: neutron-ks-user }
                patch: |
                  - op: add
                    path: /metadata/annotations/argocd.argoproj.io~1hook
                    value: Sync
                  - op: add
                    path: /metadata/annotations/argocd.argoproj.io~1hook-delete-policy
                    value: BeforeHookCreation
                  - op: remove
                    path: /metadata/annotations/helm.sh~1hook
              - target: { kind: Job, name: neutron-ks-service }
                patch: |
                  - op: add
                    path: /metadata/annotations/argocd.argoproj.io~1hook
                    value: Sync
                  - op: add
                    path: /metadata/annotations/argocd.argoproj.io~1hook-delete-policy
                    value: BeforeHookCreation
                  - op: remove
                    path: /metadata/annotations/helm.sh~1hook
              - target: { kind: Job, name: neutron-ks-endpoints }
                patch: |
                  - op: add
                    path: /metadata/annotations/argocd.argoproj.io~1hook
                    value: Sync
                  - op: add
                    path: /metadata/annotations/argocd.argoproj.io~1hook-delete-policy
                    value: BeforeHookCreation
                  - op: remove
                    path: /metadata/annotations/helm.sh~1hook
              - target: { kind: Job, name: neutron-rabbit-init }
                patch: |
                  - op: add
                    path: /metadata/annotations/argocd.argoproj.io~1hook
                    value: Sync
                  - op: add
                    path: /metadata/annotations/argocd.argoproj.io~1hook-delete-policy
                    value: BeforeHookCreation
                  - op: remove
                    path: /metadata/annotations/helm.sh~1hook
    - repoURL: {{ .Values.repos.self }}      # your GitOps repo
      targetRevision: {{ .Values.versions.self_ref | default "main" }}
      ref:  values
  syncPolicy:
    automated: { prune: true, selfHeal: true }

