apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: neutron
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: {{ .Values.project }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.namespaces.os }}
  source:
    repoURL: {{ .Values.repos.osh }}
    targetRevision: {{ .Values.versions.osh_services_ref | default "master" }}
    path: neutron
    helm:
      valueFiles:
        - $values/values/globals.yaml
        - $values/values/neutron-ovn.yaml
        - $values/values/secrets.sample.yaml
  syncPolicy:
    automated: { prune: true, selfHeal: true }

