apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: neutron
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "40"
spec:
  project: {{ .Values.project }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.namespaces.os }}
  sources:
    - repoURL: {{ .Values.repos.osh }}
      targetRevision: {{ .Values.versions.osh_services_ref | default "master" }}
      path: neutron
      helm:
        valueFiles:
          - $values/values/globals.yaml
          - $values/values/neutron-ovn.yaml 
          - $values/values/secrets/neutron.secrets.sops.yaml
        postRenderer:
          kustomize:
            patchesJson6902:
              - target:
                  group: batch
                  version: v1
                  kind: Job
                  labelSelector: application=neutron
                patch:
                  - op: remove
                    path: /metadata/annotations/helm.sh~1hook
                  - op: remove
                    path: /metadata/annotations/helm.sh~1hook-weight
                  - op: remove
                    path: /metadata/annotations/helm.sh~1hook-delete-policy
              - target:
                  kind: Deployment
                  name: neutron-server
                patch: |
                  - op: add
                    path: /spec/template/spec/volumes/-
                    value:
                      name: neutron-ovn-conn
                      configMap:
                        name: neutron-ovn-conn
                  - op: remove
                    path: /spec/template/spec/containers/0/volumeMounts
                    # custom “remove by filter”: kustomize v5+ supports this style via replacements.
                    # If not supported in your build, use the “index” method shown below.
                  - op: add
                    path: /spec/template/spec/containers/0/volumeMounts/-
                    value:
                      name: neutron-ovn-conn
                      mountPath: /etc/neutron/plugins/ml2/ml2_conf.ini
                      subPath: 99-ovn-conn.ini
                      readOnly: true
              - target:
                  kind: Deployment
                  name: neutron-rpc-server
                patch: |
                  - op: add
                    path: /spec/template/spec/volumes/-
                    value:
                      name: neutron-ovn-conn
                      configMap:
                        name: neutron-ovn-conn
                  - op: add
                    path: /spec/template/spec/containers/0/volumeMounts/-
                    value:
                      name: neutron-ovn-conn
                      mountPath: /etc/neutron/plugins/ml2/ml2_conf.ini
                      subPath: 99-ovn-conn.ini
                      readOnly: true 
    - repoURL: {{ .Values.repos.self }}
      targetRevision: {{ .Values.versions.self_ref | default "main" }}
      ref:  values
      path: manifests
      directory:
        recurse: true
        include: neutron/^^.yaml
  syncPolicy:
    automated: { prune: true, selfHeal: true }

