apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: neutron
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "40"
spec:
  project: {{ .Values.project }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.namespaces.os }}
  sources:
    - repoURL: {{ .Values.repos.self }}
      targetRevision: {{ .Values.versions.self_ref | default "main" }}
      ref:  values
    - repoURL: {{ .Values.repos.osh }}
      targetRevision: {{ .Values.versions.osh_services_ref | default "master" }}
      path: neutron
      helm:
        valueFiles:
          - $values/values/globals.yaml
          - $values/values/neutron-ovn.yaml 
          - $values/values/secrets/neutron.secrets.sops.yaml
        postRenderer:
          kustomize:
            patchesJson6902:
              - target:
                  group: batch
                  version: v1
                  kind: Job
                  labelSelector: application=neutron
                patch:
                  - op: remove
                    path: /metadata/annotations/helm.sh~1hook
                  - op: remove
                    path: /metadata/annotations/helm.sh~1hook-weight
                  - op: remove
                    path: /metadata/annotations/helm.sh~1hook-delete-policy 
  syncPolicy:
    automated: { prune: true, selfHeal: true }

