apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: glance
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "50"
spec:
  project: {{ .Values.project }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.namespaces.os }}
  source:
    repoURL: {{ .Values.repos.osh }}
    targetRevision: {{ .Values.versions.osh_services_ref | default "master" }}
    path: glance
    helm:
      valueFiles:
        - ../values/globals.yaml
        - ../values/glance-rbd.yaml
        - ../values/secrets.sample.yaml
  syncPolicy:
    automated: { prune: true, selfHeal: true }

