apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: images
  namespace: rook-ceph
spec:
  failureDomain: host
  replicated: { size: 1 }   # use 2 if only 2 OSD hosts; 1 for lab only
---
apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: volumes
  namespace: rook-ceph
spec:
  failureDomain: host
  replicated: { size: 1 }

