apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: images
  namespace: rook-ceph
spec:
  failureDomain: host
  replicated:
    size: 3
    requireSafeReplicaSize: true
  parameters:
    compression_mode: "none"
---
apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: volumes
  namespace: rook-ceph
spec:
  failureDomain: host
  replicated:
    size: 3
    requireSafeReplicaSize: true
  parameters:
    compression_mode: "none"
