apiVersion: apps/v1
kind: Deployment
metadata:
  name: rook-ceph-tools
  namespace: rook-ceph
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rook-ceph-tools
  template:
    metadata:
      labels:
        app: rook-ceph-tools
    spec:
      serviceAccountName: rook-ceph-system
      containers:
      - name: rook-ceph-tools
        image: quay.io/ceph/ceph:v19
        imagePullPolicy: IfNotPresent
        command: ["/tini","--","/usr/local/bin/toolbox.sh"]
        volumeMounts:
        - name: mon-endpoints
          mountPath: /etc/ceph
      volumes:
      - name: mon-endpoints
        configMap:
          name: rook-ceph-mon-endpoints
