apiVersion: apps/v1
kind: Deployment
metadata:
  name: rook-ceph-tools
  namespace: rook-ceph
  labels:
    app: rook-ceph-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rook-ceph-tools
  template:
    metadata:
      labels:
        app: rook-ceph-tools
    spec:
      serviceAccountName: rook-ceph-system
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: rook-ceph-tools
        image: quay.io/ceph/ceph:v19
        imagePullPolicy: IfNotPresent
        command: ["/bin/bash","-lc","sleep infinity"]
        securityContext:
          privileged: true
        volumeMounts:
        - name: ceph-conf
          mountPath: /etc/ceph
      volumes:
      - name: ceph-conf
        projected:
          sources:
          - configMap:
              name: rook-ceph-config
          - secret:
              name: rook-ceph-mon
